server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/case_db
    username: postgres
    password: "qwerty123@"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html